name: mychess
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'
 
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_chess_board: ^1.0.1
  flutter_native_splash: ^2.2.19
flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#ffffff"
  # background_image: "assets/images/splash.png"
  image: "assets/images/splash.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^2.0.0
 
flutter:

  uses-material-design: true
 
  assets:
    - assets/images/
 